Repository Studio-Yandex-Practicum/maxboom_frontend, pull requests merged in 2023-12, with the labels that each got.

#119 fix: исправлено закрытие всех модалок по Esc; добавлен focus-trap; компонент переименован в Modal
  package-lock.json
  package.json
  src/components/CardPreview/CardPreview.module.scss
  src/components/CardPreview/CardPreview.tsx
  src/components/HeaderAccount/HeaderAccount.tsx
  src/components/WidgetButtonsFunctions/WidgetButtonsFunctions.tsx
  src/components/WidgetButtonsPurchase/WidgetButtonsPurchase.tsx
  src/features/login/ui/LoginForm/LoginForm.tsx
  src/pages/ProductsPage/ProductsPage.tsx
  src/shared/ui/Button/Button.module.scss
  src/shared/ui/Button/Button.stories.tsx
  src/shared/ui/Button/Button.tsx
  src/shared/ui/Modal/Modal.module.scss
  src/shared/ui/Modal/Modal.tsx
  src/ui/Popup/Popup.tsx
Labels: bug

#126 Универсальный компонент Link в shared слой
  src/assets/icons/ArrowReadNext.svg
  src/assets/icons/IconCategories.svg
  src/components/AdvantageCard/AdvantageCard.tsx
  src/components/ArticleBlock/ArticleBlock.tsx
  src/components/BlogItemForContainer/BlogItemForContainer.tsx
  src/components/BlogMainItem/BlogMainItem.tsx
  src/components/BrandBlock/BrandBlock.tsx
  src/components/CardForContainer/CardForContainer.tsx
  src/components/CardReview/CardReview.tsx
  src/components/CatalogLink/CatalogLink.tsx
  src/components/CategoryList/CategoryList.tsx
  src/components/ContainerCards/ContainerCards.tsx
  src/components/Footer/Footer.tsx
  src/components/PageDescription/PageDescription.tsx
  src/components/ReviewsBlock/ReviewsBlock.tsx
  src/components/SearchItem/SearchItem.tsx
  src/components/Slider/Slider.tsx
  src/components/header/header.tsx
  src/components/logo/Logo.tsx
  src/components/searchResult/searchResult.tsx
  src/features/login/ui/LoginForm/LoginForm.tsx
  src/shared/ui/Link/Link.module.scss
  src/shared/ui/Link/Link.stories.tsx
  src/shared/ui/Link/Link.tsx
  src/ui/link/index.tsx
Labels: refactoring

#127 Поправил верстку header, MainPage, ProductsPage, BlogPage
  src/components/ArticleBlock/articleBlock.module.scss
  src/components/BlogItemForContainer/blog-item-for-container.module.scss
  src/components/BlogMain/BlogMain.tsx
  src/components/BlogMain/blog-main.module.scss
  src/components/Footer/footer.module.scss
  src/components/ProductCard/ProductCard.module.scss
  src/components/ProductCard/ProductCard.tsx
  src/components/ReviewsBlock/ReviewsBlock.module.scss
  src/components/Slider/slider.module.scss
  src/components/header/header.module.scss
  src/components/search/search.module.scss
  src/pages/RootPage/root.module.scss
Labels: bug

#130 Добавлен компонент Spinner для использования в Suspense/fallback
  src/components/CardPreview/CardPreview.tsx
  src/components/HeaderAccount/HeaderAccount.tsx
  src/pages/ProductsPage/ProductsPage.tsx
  src/shared/ui/Spinner/Spinner.module.scss
  src/shared/ui/Spinner/Spinner.stories.tsx
  src/shared/ui/Spinner/Spinner.tsx
Labels: enhancement

#133 development: Добавить сетку с категориями
  src/assets/images/categoryCards/img-categories-01-210x263.webp
  src/assets/images/categoryCards/img-categories-02-171x252.webp
  src/assets/images/categoryCards/img-categories-03-187x325.webp
  src/assets/images/categoryCards/img-categories-04-180x252.webp
  src/assets/images/categoryCards/img-categories-05-197x300.webp
  src/assets/images/categoryCards/img-categories-06-235x325.webp
  src/assets/styles/utils/_mixins.scss
  src/assets/styles/utils/_variables.scss
  src/components/ContextMenuElement/contextMenuElement.module.scss
  src/components/header/header.tsx
  src/components/searchResult/searchResult.module.scss
  src/components/searchResult/searchResult.tsx
  src/entities/СontactCard/СontactCard.tsx
  src/mockData/catalogListData.ts
  src/mockData/searchData.ts
  src/models/CategoryModel.ts
  src/models/MessengerModel.ts
  src/pages/MainPage/MainPage.tsx
  src/shared/config/catalogLinks/catalogLinks.ts
  src/shared/ui/CategoryCard/constants/constants.ts
  src/shared/ui/CategoryCard/ui/CategoryCard.module.scss
  src/shared/ui/CategoryCard/ui/CategoryCard.tsx
  src/utils/messengerArray.tsx
  src/utils/types.ts
  src/widgets/CategoryGrid/CategoryGrid.module.scss
  src/widgets/CategoryGrid/CategoryGrid.tsx
Labels: development

#134 refactor: В компоненте header меню сверстано по семантике
  src/components/HeaderAccount/HeaderAccount.tsx
  src/components/PageDescription/PageDescription.module.scss
  src/components/WrapperForMainContent/wrapper.module.scss
  src/components/header/header.module.scss
  src/pages/BlogPage/BlogPage.tsx
  src/pages/CartPage/CartPage.module.scss
  src/pages/CartPage/CartPage.tsx
  src/pages/ComparePage/ComparePage.module.scss
  src/pages/ComparePage/ComparePage.tsx
  src/pages/FavoritesPage/FavoritesPage.module.scss
  src/pages/FavoritesPage/FavoritesPage.tsx
  src/pages/LoginPage/LoginPage.module.scss
  src/pages/LoginPage/LoginPage.tsx
  src/pages/ProductsPage/ProductsPage.module.scss
  src/pages/ProductsPage/ProductsPage.tsx
  src/router/index.tsx
  src/shared/config/routerConfig/routes.ts
Labels: bug, refactoring

#104 #88 Убрать из верстки svg
  package-lock.json
  src/assets/icons/IconCompare.svg
  src/assets/images/articleBlock/arrow.svg
  src/assets/images/blogMainItem/img-article-02-1500x1000.webp
  src/assets/images/blogPage/img-blog-05.svg
  src/assets/images/blogPage/img-blog-05.webp
  src/assets/images/blogPage/img-blog-06.svg
  src/assets/images/blogPage/img-blog-06.webp
  src/assets/images/blogPage/img-blog-07.svg
  src/assets/images/blogPage/img-blog-07.webp
  src/assets/images/blogPage/img-blog-08.svg
  src/assets/images/blogPage/img-blog-08.webp
  src/assets/images/blogPage/img-blog-09.svg
  src/assets/images/blogPage/img-blog-09.webp
  src/assets/images/blogPage/img-blog-10.svg
  src/assets/images/blogPage/img-blog-10.webp
  src/assets/images/header/all-categories.svg
  src/components/ArticleBlock/ArticleBlock.tsx
  src/components/BlogMain/BlogMain.tsx
  src/components/BlogMainItem/BlogMainItem.tsx
  src/components/CardPreviewHeader/CardPreviewHeader.tsx
  src/components/WidgetButtonsFunctions/WidgetButtonsFunctions.tsx
  src/components/header/header.tsx
  src/mockData/blogPageData.ts
Labels: refactoring
