Repository Studio-Yandex-Practicum/maxboom_frontend, pull requests merged in 2024-03, with the labels that each got.

#246 категории под FSD
  src/entities/SearchResult/SearchResult.tsx
  src/mockData/catalogListData.ts
  src/shared/config/catalogLinks/catalogLinks.ts
  src/shared/mockData/catalogListData.ts
  src/shared/mockData/coreBaseData.ts
  src/shared/mockData/headerAccountData.ts
  src/shared/model/CategoryModel.ts
  src/shared/model/types/common.ts
  src/shared/ui/CategoryCard/ui/CategoryCard.tsx
  src/widgets/CategoryGrid/CategoryGrid.tsx
  src/widgets/Header/Header.tsx
Labels: enhancement, refactoring

#235 #137-enhancement-Slider-changed-to-fsd
  src/app/providers/StoreProvider/config/store.ts
  src/assets/icons/ArrowRightNextPage.svg
  src/assets/images/slider/info-slide.png
  src/components/Arrows/Arrows.tsx
  src/components/Arrows/arrow.module.scss
  src/components/Dots/Dots.tsx
  src/components/Slider/Slider.tsx
  src/components/Slider/slider.module.scss
  src/components/SliderBlock/SliderBlock.tsx
  src/components/SliderBlock/slider-block.module.scss
  src/entities/HeroCard/HeroCard.module.scss
  src/entities/HeroCard/HeroCard.stories.tsx
  src/entities/HeroCard/HeroCard.tsx
  src/entities/HeroInfo/HeroInfo.module.scss
  src/entities/HeroInfo/HeroInfo.stories.tsx
  src/entities/HeroInfo/HeroInfo.tsx
  src/features/Slider/model/types.ts
  src/features/Slider/ui/Dot/Dot.module.scss
  src/features/Slider/ui/Dot/Dot.tsx
  src/features/Slider/ui/Slider/Slider.module.scss
  src/features/Slider/ui/Slider/Slider.stories.tsx
  src/features/Slider/ui/Slider/Slider.tsx
  src/mockData/heroData.ts
  src/pages/MainPage/MainPage.tsx
  src/shared/api/types.ts
  src/widgets/HeroBlock/ui/HeroBlock/HeroBlock.module.scss
  src/widgets/HeroBlock/ui/HeroBlock/HeroBlock.stories.tsx
  src/widgets/HeroBlock/ui/HeroBlock/HeroBlock.tsx
Labels: enhancement

#247 Development 217 product page api
  src/features/RollUp/RollUp.module.scss
  src/features/RollUp/RollUp.tsx
  src/pages/ProductPage/ProductPage.tsx
  src/pages/ProductPage/model/slice/productSlice.ts
Labels: api

#248 Api 144 add api to category grid
  src/app/providers/StoreProvider/config/StateSchema.ts
  src/app/providers/StoreProvider/config/store.ts
  src/entities/SearchResult/SearchResult.tsx
  src/mockData/searchData.ts
  src/shared/api/types.ts
  src/shared/model/types/CategoryModel.ts
  src/shared/model/types/common.ts
  src/shared/ui/CategoryCard/ui/CategoryCard.tsx
  src/widgets/CategoryGrid/CategoryGrid.tsx
  src/widgets/CategoryGrid/model/selectors/selectors.tsx
  src/widgets/CategoryGrid/model/services/getCategoryList.tsx
  src/widgets/CategoryGrid/model/slice/categoryGridSlice.tsx
  src/widgets/CategoryGrid/model/types/types.tsx
  src/widgets/Header/model/slice/headerSlice.tsx
Labels: enhancement, api

#240 №222 create form return
  package-lock.json
  package.json
  src/app/router/AppRouter/ui/AppRouter.tsx
  src/features/Contacts/Contacts.tsx
  src/features/login/model/validation/validation.ts
  src/pages/HelpPage/HelpPage.module.scss
  src/pages/HelpPage/HelpPage.tsx
  src/shared/config/routerConfig/routes.ts
  src/shared/model/types/common.ts
  src/shared/ui/Button/Button.module.scss
  src/shared/ui/Button/Button.stories.tsx
  src/shared/ui/Button/Button.tsx
  src/shared/ui/Checkbox/Checkbox.module.scss
  src/shared/ui/Checkbox/Checkbox.stories.tsx
  src/shared/ui/Checkbox/Checkbox.tsx
  src/shared/ui/Label/Label.tsx
  src/stories/Configure.mdx
  src/stories/assets/avif-test-image.avif
  src/stories/button.css
  src/stories/header.css
  src/widgets/FormReturn/FormReturn.module.scss
  src/widgets/FormReturn/FormReturn.stories.tsx
  src/widgets/FormReturn/FormReturn.tsx
  src/widgets/HelpCategories/HelpCategories.module.scss
  src/widgets/HelpCategories/HelpCategories.stories.tsx
  src/widgets/HelpCategories/HelpCategories.tsx
Labels: верстка

#258 #257-development-BannerBlock-done
  src/assets/images/banner/banner.png
  src/entities/BannerCard/BannerCard.module.scss
  src/entities/BannerCard/BannerCard.stories.tsx
  src/entities/BannerCard/BannerCard.tsx
  src/mockData/bannerData.ts
  src/pages/MainPage/MainPage.tsx
  src/widgets/BannerBlock/ui/BannerBlock.module.scss
  src/widgets/BannerBlock/ui/BannerBlock.stories.tsx
  src/widgets/BannerBlock/ui/BannerBlock.tsx
Labels: development

#261 №249 create cart component
  package.json
  src/app/router/AppRouter/ui/AppRouter.tsx
  src/pages/ContactsPage/ContactsPage.module.scss
  src/pages/ContactsPage/ContactsPage.tsx
  webpack.config.js
Labels: верстка

#273 Enhancement 266 feedback page
  src/app/providers/StoreProvider/config/StateSchema.ts
  src/app/providers/StoreProvider/config/store.ts
  src/app/router/AppRouter/ui/AppRouter.tsx
  src/entities/FeedbackCard/FeedbackCard.module.scss
  src/entities/FeedbackCard/FeedbackCard.stories.tsx
  src/entities/FeedbackCard/FeedbackCard.tsx
  src/entities/FeedbackCard/model/functions/functions.ts
  src/entities/FeedbackCard/model/types/types.ts
  src/entities/FeedbackCard/ui/ScorePopup/ScorePopup.module.scss
  src/entities/FeedbackCard/ui/ScorePopup/ScorePopup.tsx
  src/pages/FeedbackPage/FeedbackPage.module.scss
  src/pages/FeedbackPage/FeedbackPage.tsx
  src/pages/FeedbackPage/model/slice/feedbackSlice.ts
  src/pages/FeedbackPage/model/types/types.ts
  src/widgets/FeedbackList/FeedbackList.module.scss
  src/widgets/FeedbackList/FeedbackList.tsx
  src/widgets/FeedbackList/model/types/types.ts
  src/widgets/ReviewsBlock/model/services/getStoreReviews.ts
  src/widgets/ReviewsBlock/ui/ReviewsBlock/ReviewsBlock.tsx
Labels: enhancement

#276 Enhancement 152 main page
  src/pages/MainPage/MainPage.tsx
  src/pages/ProductPage/ProductPage.tsx
  src/shared/constants/constants.ts
  src/widgets/ViewedProducts/ViewedProducts.module.scss
  src/widgets/ViewedProducts/ViewedProducts.tsx
  src/widgets/ViewedProducts/model/functions/functions.ts
  src/widgets/ViewedProducts/model/types/types.ts
Labels: enhancement

#279 #278-enhancement-adapted-HeroBlock-BannerBlock
  src/components/WrapperForMainContent/wrapper.module.scss
  src/entities/BannerCard/BannerCard.module.scss
  src/entities/HeroCard/HeroCard.module.scss
  src/entities/HeroInfo/HeroInfo.module.scss
  src/features/Slider/ui/Slider/Slider.module.scss
  src/mockData/heroData.ts
  src/shared/styles/utils/_mixins.scss
  src/ui/img/img.module.scss
  src/widgets/BannerBlock/ui/BannerBlock.module.scss
  src/widgets/HeroBlock/ui/HeroBlock/HeroBlock.module.scss
  src/widgets/HeroBlock/ui/HeroBlock/HeroBlock.tsx
Labels: enhancement
