Repository Studio-Yandex-Practicum/maxboom_frontend, pull requests merged in 2024-04, with the labels that each got.

#262 #259-enhancement-hid-Blocks-on-MainPage
  src/entities/BannerCard/BannerCard.stories.tsx
  src/entities/BannerCard/BannerCard.tsx
  src/mockData/bannerData.ts
  src/widgets/BannerBlock/ui/BannerBlock.tsx
  src/widgets/BlogBlock/model/services/getBlogPosts.ts
  src/widgets/BlogBlock/ui/BlogBlock.tsx
  src/widgets/BrandBlock/ui/BrandBlock/BrandBlock.tsx
  src/widgets/NewsBlock/model/services/getShopNews.ts
  src/widgets/NewsBlock/ui/NewsBlock.tsx
  src/widgets/ReviewsBlock/model/services/getStoreReviews.ts
  src/widgets/ReviewsBlock/ui/ReviewsBlock/ReviewsBlock.tsx
  src/widgets/StoriesBlock/model/services/getStories.ts
  src/widgets/StoriesBlock/ui/StoriesBlock.tsx
Labels: enhancement

#282 Enhancement 270 feedback page
  src/app/providers/StoreProvider/config/StateSchema.ts
  src/app/providers/StoreProvider/config/store.ts
  src/pages/FeedbackPage/FeedbackPage.module.scss
  src/pages/FeedbackPage/FeedbackPage.tsx
  src/shared/constants/constants.ts
  src/shared/ui/FormMsg/FormMsg.module.scss
  src/shared/ui/FormMsg/FormMsg.stories.tsx
  src/shared/ui/FormMsg/FormMsg.tsx
  src/widgets/AveregeMark/AveregeMark.module.scss
  src/widgets/FeedbackForm/FeedbackForm.module.scss
  src/widgets/FeedbackForm/FeedbackForm.stories.tsx
  src/widgets/FeedbackForm/FeedbackForm.tsx
  src/widgets/FeedbackForm/model/constants/constants.ts
  src/widgets/FeedbackForm/model/functions/functions.ts
  src/widgets/FeedbackForm/model/scheme/feedbackFormScheme.ts
  src/widgets/FeedbackForm/model/scheme/feedbackFormSliceSchema.ts
  src/widgets/FeedbackForm/model/slice/feedbackFormSlice.ts
  src/widgets/FeedbackForm/model/types/types.ts
  src/widgets/FeedbackForm/ui/FeedbackFormRadioGroup/FeedbackFormRadioGroup.module.scss
  src/widgets/FeedbackForm/ui/FeedbackFormRadioGroup/FeedbackFormRadioGroup.tsx
  src/widgets/FeedbackForm/ui/RequiredFieldTitle/RequiredFieldTitle.module.scss
  src/widgets/FeedbackForm/ui/RequiredFieldTitle/RequiredFieldTitle.tsx
Labels: enhancement, api

#295 Enhancement 284 feedback page
  src/entities/FeedbackCard/FeedbackCard.module.scss
  src/entities/FeedbackCard/FeedbackCard.tsx
  src/pages/FeedbackPage/FeedbackPage.module.scss
  src/pages/FeedbackPage/FeedbackPage.tsx
  src/pages/FeedbackPage/ui/FeedbackFormPopup/FeedbackFormPopup.module.scss
  src/pages/FeedbackPage/ui/FeedbackFormPopup/FeedbackFormPopup.tsx
  src/shared/libs/helpers/popupHelper.ts
  src/widgets/AveregeMark/AveregeMark.module.scss
Labels: enhancement

#296 #293-enhancement-create-Breadcrumbs-Component
  src/components/PageDescription/PageDescription.tsx
  src/shared/ui/Breadcrumbs/Breadcrumbs.module.scss
  src/shared/ui/Breadcrumbs/Breadcrumbs.stories.tsx
  src/shared/ui/Breadcrumbs/Breadcrumbs.tsx
Labels: enhancement

#297 enhancement_280-1_page_vouchers
  src/app/router/AppRouter/ui/AppRouter.tsx
  src/pages/VouchersPage/VouchersPage.module.scss
  src/pages/VouchersPage/VouchersPage.tsx
  src/widgets/FormBuyGiftCertificate/model/types/types.ts
  src/widgets/FormBuyGiftCertificate/model/validation/validation.ts
  src/widgets/FormBuyGiftCertificate/ui/FormBuyGiftCertificate.module.scss
  src/widgets/FormBuyGiftCertificate/ui/FormBuyGiftCertificate.tsx
  src/widgets/Header/Header.tsx
Labels: enhancement, верстка

#302 Исправлен баг с назначением стиля по имени элемента div
  src/shared/ui/FormMsg/FormMsg.module.scss
Labels: bug

#299 enhancement_221_api_about_us
  src/app/providers/StoreProvider/config/StateSchema.ts
  src/app/providers/StoreProvider/config/store.ts
  src/app/router/AppRouter/ui/AppRouter.tsx
  src/entities/AboutUs/model/types/types.ts
  src/entities/AboutUs/ui/AboutUs.module.scss
  src/entities/AboutUs/ui/AboutUs.tsx
  src/pages/AboutUsPage/AboutUsPage.module.scss
  src/pages/AboutUsPage/AboutUsPage.tsx
  src/pages/AboutUsPage/model/selectors/selectors.ts
  src/pages/AboutUsPage/model/services/getAboutUs.tsx
  src/pages/AboutUsPage/model/slice/aboutUsSlice.tsx
  src/pages/AboutUsPage/model/types/types.ts
  src/shared/api/types.ts
Labels: enhancement

#320 enhancement_307_fix_routing_at_header_icon
  src/shared/ui/logo/Logo.tsx
  src/widgets/Footer/Footer.tsx
  src/widgets/Header/Header.tsx
  src/widgets/Header/model/slice/headerSlice.tsx
  src/widgets/Header/model/types/types.tsx
Labels: bug

#324 Добавил breadcrumbs на страницу товара. Немного поправил компонент br…
  src/pages/ProductPage/ProductPage.module.scss
  src/pages/ProductPage/ProductPage.tsx
  src/shared/ui/Breadcrumbs/Breadcrumbs.module.scss
  src/shared/ui/Breadcrumbs/Breadcrumbs.tsx
Labels: enhancement

#328 Key был задан не у корневого элемента в списке и возникала ошибка.
  src/shared/ui/Breadcrumbs/Breadcrumbs.tsx
Labels: bug

#321 Development 291 add to cart
  src/app/App.tsx
  src/app/providers/StoreProvider/config/StateSchema.ts
  src/app/providers/StoreProvider/config/store.ts
  src/entities/CartEntity/model/functions/cartHelper.ts
  src/entities/CartEntity/model/hooks/cartHooks.ts
  src/entities/CartEntity/model/hooks/sliceHooks.ts
  src/entities/CartEntity/model/slice/cartEntitySlice.ts
  src/entities/CartEntity/model/types/types.ts
  src/features/ProductImgCarousel/ProductImgCarousel.module.scss
  src/features/ProductImgCarousel/ui/PreviewCarousel/PreviewCarousel.module.scss
  src/features/ProductImgCarousel/ui/PreviewCarousel/PreviewCarousel.tsx
  src/features/WidgetButtonsPurchase/WidgetButtonsPurchase.module.scss
  src/features/WidgetButtonsPurchase/WidgetButtonsPurchase.tsx
  src/pages/AboutUsPage/AboutUsPage.tsx
  src/pages/FeedbackPage/FeedbackPage.tsx
  src/pages/ProductPage/ProductPage.tsx
  src/shared/api/api.ts
  src/widgets/FeedbackForm/FeedbackForm.tsx
  src/widgets/Product/Product.module.scss
  src/widgets/Product/Product.tsx
  src/widgets/Product/ui/PopupImg/PopupImg.tsx
  src/widgets/ProductItem/CardPreview/CardPreview.module.scss
  src/widgets/ProductItem/CardPreview/CardPreview.tsx
  src/widgets/ProductItem/CardPreview/CardPrewiew.stories.tsx
  src/widgets/ProductItem/ProductItem.stories.tsx
  src/widgets/ProductItem/ProductItem.tsx
  src/widgets/ProductsList/ProductsList.tsx
  src/widgets/ViewedProducts/ViewedProducts.tsx
  webpack.config.js
Labels: api

#331 Доавил breadcrumbs на страницу отзывов
  src/pages/FeedbackPage/FeedbackPage.module.scss
  src/pages/FeedbackPage/FeedbackPage.tsx
Labels: enhancement
