Repository Studio-Yandex-Practicum/maxboom_frontend, pull requests merged in 2024-01, with the labels that each got.

#181 #180-enhancement-add-storybooks-to-reviewsBlock
  src/entities/CardReview/ui/CardReview/CardReview.stories.tsx
  src/shared/ui/ButtonDots/ButtonDots.stories.tsx
  src/shared/ui/Heading/Heading.stories.tsx
  src/shared/ui/Paragraph/Paragraph.stories.tsx
  src/shared/ui/Subheading/Subheading.stories.tsx
  src/widgets/ReviewsBlock/ui/ReviewsBlock/ReviewsBlock.stories.tsx
Labels: enhancement

#175 refactor: Выделить из Header отдельную feature - SearchProduct
  src/components/SearchItem/search-item.module.scss
  src/components/header/header.tsx
  src/components/search/search.tsx
  src/entities/SearchItem/SearchItem.module.scss
  src/entities/SearchItem/SearchItem.stories.tsx
  src/entities/SearchItem/SearchItem.tsx
  src/features/SearchProduct/index.tsx
  src/features/SearchProduct/ui/SearchProduct.module.scss
  src/features/SearchProduct/ui/SearchProduct.stories.tsx
  src/features/SearchProduct/ui/SearchProduct.tsx
  src/widgets/SearchResult/SearchResult.module.scss
  src/widgets/SearchResult/SearchResult.stories.tsx
  src/widgets/SearchResult/SearchResult.tsx
Labels: refactoring

#178 #176 bugfix: исправление бага недоступности воздействия на область под скрытым меню контактов
  src/entities/ContactCard/ContactCard.tsx
  src/entities/ContactCard/contactCard.module.scss
  src/features/Contacts/Contacts.tsx
  src/features/Contacts/contacts.module.scss
Labels: bug

#179 #149 Переделка компонента Бренды по fsd
  src/assets/images/brands/brand-without-image.webp
  src/components/BrandBlock/BrandBlock.tsx
  src/entities/BrandCard/BrandCard.module.scss
  src/entities/BrandCard/BrandCard.stories.tsx
  src/entities/BrandCard/BrandCard.tsx
  src/entities/constants/constants.tsx
  src/mockData/brandData.ts
  src/models/BrandModel.ts
  src/pages/MainPage/MainPage.tsx
  src/shared/config/routerConfig/routes.ts
  src/shared/constants/constants.ts
  src/widgets/BrandBlock/BrandBlock.module.scss
  src/widgets/BrandBlock/BrandBlock.stories.tsx
  src/widgets/BrandBlock/BrandBlock.tsx
Labels: enhancement, refactoring, верстка

#187 поправить верстку subscribeForm
  src/entities/SubscribeForm/SubscribeForm.tsx
  src/entities/SubscribeForm/subscribeForm.module.scss
  src/features/SubscribeForm/subscribeForm.module.scss
Labels: refactoring

#189 #146-api-inserted-to-ReviewsBlock
  src/app/providers/SroreProvider/config/StateSchema.ts
  src/app/providers/SroreProvider/config/store.ts
  src/entities/CardReview/ui/CardReview/CardReview.stories.tsx
  src/entities/CardReview/ui/CardReview/CardReview.tsx
  src/pages/MainPage/MainPage.tsx
  src/shared/api/types.ts
  src/widgets/ReviewsBlock/model/selectors/selectors.ts
  src/widgets/ReviewsBlock/model/services/getStoreReviews.ts
  src/widgets/ReviewsBlock/model/slice/reviewsSlice.ts
  src/widgets/ReviewsBlock/model/types/types.ts
  src/widgets/ReviewsBlock/ui/ReviewsBlock/ReviewsBlock.stories.tsx
  src/widgets/ReviewsBlock/ui/ReviewsBlock/ReviewsBlock.tsx
Labels: api

#203 #141-enhancement-changed-component-NewsBlock-to-fsd
  src/entities/NewsCard/NewsCard.module.scss
  src/entities/NewsCard/NewsCard.stories.tsx
  src/entities/NewsCard/NewsCard.tsx
  src/models/SvgModel.ts
  src/pages/MainPage/MainPage.tsx
  src/shared/ui/Scroll/Scroll.module.scss
  src/shared/ui/Scroll/Scroll.stories.tsx
  src/shared/ui/Scroll/Scroll.tsx
  src/widgets/NewsBlock/ui/NewsBlock.module.scss
  src/widgets/NewsBlock/ui/NewsBlock.stories.tsx
  src/widgets/NewsBlock/ui/NewsBlock.tsx
Labels: enhancement

#202 api: Интеграция с бэком для отправки поискового запроса
  config/storybook/decorators/StoreDecorator.js
  src/app/providers/StoreProvider/config/StateSchema.ts
  src/app/providers/StoreProvider/config/store.ts
  src/app/providers/StoreProvider/index.ts
  src/app/providers/StoreProvider/ui/StoreProvider.tsx
  src/app/router/AppRouter/ui/AppRouter.tsx
  src/components/header/header.tsx
  src/entities/Category/selectors/categorySelectors.ts
  src/entities/Category/slice/categorySlice.ts
  src/features/SearchProduct/selectors/searchProductSelectors.ts
  src/features/SearchProduct/slice/searchProductSlice.ts
  src/features/SearchProduct/types/types.ts
  src/features/SearchProduct/ui/SearchProduct.tsx
  src/features/login/model/selectors/getUserAuthStatus.ts
  src/features/login/model/services/loginByUsername/loginByUsername.ts
  src/features/login/model/services/logout/logout.ts
  src/index.tsx
  src/pages/ProductsPage/ProductsPage.tsx
  src/pages/SearchResultsPage/SearchResultsPage.module.scss
  src/pages/SearchResultsPage/SearchResultsPage.tsx
  src/shared/api/types.ts
  src/shared/config/routerConfig/routes.ts
  src/shared/libs/hooks/store.ts
  src/widgets/ReviewsBlock/model/selectors/selectors.ts
  src/widgets/ReviewsBlock/model/services/getStoreReviews.ts
Labels: development, api

#197 #150 enhancement: добавить api к BrandBlock через thunk, redux.
  src/app/providers/StoreProvider/config/StateSchema.ts
  src/app/providers/StoreProvider/config/store.ts
  src/entities/BrandCard/BrandCard.module.scss
  src/entities/BrandCard/BrandCard.tsx
  src/entities/constants/constants.tsx
  src/pages/MainPage/MainPage.tsx
  src/shared/api/types.ts
  src/shared/constants/constants.ts
  src/widgets/BrandBlock/selectors/selectors.ts
  src/widgets/BrandBlock/slice/brandSlice.ts
  src/widgets/BrandBlock/types/types.ts
  src/widgets/BrandBlock/ui/BrandBlock/BrandBlock.module.scss
  src/widgets/BrandBlock/ui/BrandBlock/BrandBlock.stories.tsx
  src/widgets/BrandBlock/ui/BrandBlock/BrandBlock.tsx
Labels: enhancement, api
