Repository Studio-Yandex-Practicum/maxboom_frontend, pull requests merged in 2024-02, with the labels that each got.

#205 #200-enhancement-changed-StoriesBlock-to-fsd
  src/entities/StoryCard/StoryCard.module.scss
  src/entities/StoryCard/StoryCard.stories.tsx
  src/entities/StoryCard/StoryCard.tsx
  src/pages/MainPage/MainPage.tsx
  src/widgets/StoriesBlock/ui/StoriesBlock.module.scss
  src/widgets/StoriesBlock/ui/StoriesBlock.stories.tsx
  src/widgets/StoriesBlock/ui/StoriesBlock.tsx
Labels: enhancement

#208 внедрить Api в footer
  src/app/providers/StoreProvider/config/StateSchema.ts
  src/app/providers/StoreProvider/config/store.ts
  src/shared/api/types.ts
  src/widgets/Footer/Footer.tsx
  src/widgets/Footer/model/selectors/selectors.ts
  src/widgets/Footer/model/services/getCoreBase.tsx
  src/widgets/Footer/model/slice/footerSlice.ts
  src/widgets/Footer/model/types/types.tsx
Labels: enhancement, api

#232 #211-product-card-in-fsd
  config/build/loaders/buildCssLoader.cjs
  src/assets/icons/IconArrow.tsx
  src/components/BlogCategories/blog-categories.module.scss
  src/entities/AdvantageCard/ui/AdvantageCard/advantageCard.module.scss
  src/entities/BlogCard/BlogCard.module.scss
  src/entities/BrandCard/BrandCard.module.scss
  src/entities/CardReview/ui/CardReview/cardReview.module.scss
  src/entities/ContactCard/contactCard.module.scss
  src/entities/NewsCard/NewsCard.module.scss
  src/entities/ProductEntity/ui/ProductEntity/ProductEntity.module.scss
  src/entities/StoryCard/StoryCard.module.scss
  src/features/CardPreviewFooter/CardPreviewFooter.module.scss
  src/features/CardPreviewFooter/CardPreviewFooter.tsx
  src/features/CardPreviewHeader/CardPreviewHeader.module.scss
  src/features/CardPreviewHeader/CardPreviewHeader.tsx
  src/features/CartCouponApply/ui/CartCouponApply/CartCouponApply.module.scss
  src/features/CartEdit/ui/CartEdit/CartEdit.module.scss
  src/features/Contacts/contacts.module.scss
  src/features/ProductAvailability/ProductAvailability.module.scss
  src/features/ProductAvailability/ProductAvailability.tsx
  src/features/QuickPurchase/ui/QuickPurchaseForm/QuickPurchaseForm.module.scss
  src/features/WidgetButtonsFunctions/WidgetButtonsFunctions.module.scss
  src/features/WidgetButtonsFunctions/WidgetButtonsFunctions.stories.tsx
  src/features/WidgetButtonsFunctions/WidgetButtonsFunctions.tsx
  src/features/WidgetButtonsPurchase/WidgetButtonsPurchase.module.scss
  src/features/WidgetButtonsPurchase/WidgetButtonsPurchase.stories.tsx
  src/features/WidgetButtonsPurchase/WidgetButtonsPurchase.tsx
  src/pages/CartPage/CartPage.module.scss
  src/pages/ProductsPage/ProductsPage.tsx
  src/shared/api/types.ts
  src/shared/styles/utils/_variables.scss
  src/shared/ui/ButtonDots/ButtonDots.module.scss
  src/shared/ui/Heading/Heading.tsx
  src/shared/ui/Heading/heading.module.scss
  src/shared/ui/ProductLabels/ProductLabels.module.scss
  src/shared/ui/ProductLabels/ProductLabels.stories.tsx
  src/shared/ui/ProductLabels/ProductLabels.tsx
  src/shared/ui/ProductLabels/utils/utils.ts
  src/shared/ui/Scroll/Scroll.module.scss
  src/shared/ui/Subheading/subheading.module.scss
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.tsx
  src/stories/Page.tsx
  src/widgets/Advantages/ui/Advantages/advantages.module.scss
  src/widgets/BlogBlock/ui/BlogBlock.module.scss
  src/widgets/Carousel/Carousel.module.scss
  src/widgets/Carousel/Carousel.stories.tsx
  src/widgets/Carousel/Carousel.tsx
  src/widgets/MakeOrder/ui/MakeOrder/MakeOrder.module.scss
  src/widgets/NewsBlock/ui/NewsBlock.module.scss
  src/widgets/ProductItem/CardPreview/CardPreview.module.scss
  src/widgets/ProductItem/CardPreview/CardPreview.tsx
  src/widgets/ProductItem/CardPreview/CardPrewiew.stories.tsx
  src/widgets/ProductItem/ProductItem.module.scss
  src/widgets/ProductItem/ProductItem.stories.tsx
  src/widgets/ProductItem/ProductItem.tsx
  src/widgets/ReviewsBlock/ui/ReviewsBlock/reviewsBlock.module.scss
  src/widgets/StoriesBlock/ui/StoriesBlock.module.scss
Labels: enhancement

#228 #210-api-inserted-to-StoriesBlock
  src/app/providers/StoreProvider/config/StateSchema.ts
  src/app/providers/StoreProvider/config/store.ts
  src/entities/BlogCard/BlogCard.module.scss
  src/entities/NewsCard/NewsCard.module.scss
  src/entities/StoryCard/StoryCard.module.scss
  src/entities/StoryCard/StoryCard.stories.tsx
  src/entities/StoryCard/StoryCard.tsx
  src/shared/api/types.ts
  src/widgets/BlogBlock/ui/BlogBlock.module.scss
  src/widgets/NewsBlock/model/slice/shopNewsSlice.ts
  src/widgets/NewsBlock/model/types/types.ts
  src/widgets/ReviewsBlock/model/slice/reviewsSlice.ts
  src/widgets/ReviewsBlock/model/types/types.ts
  src/widgets/StoriesBlock/model/selectors/selectors.ts
  src/widgets/StoriesBlock/model/services/getStories.ts
  src/widgets/StoriesBlock/model/slice/storiesSlice.ts
  src/widgets/StoriesBlock/model/types/types.ts
  src/widgets/StoriesBlock/ui/StoriesBlock.tsx
Labels: api

#238 переделать ArticleBlock по FSD
  src/pages/MainPage/MainPage.tsx
  src/widgets/ArticleBlock/ArticleBlock.tsx
  src/widgets/ArticleBlock/articleBlock.module.scss
Labels: enhancement
