Repository Studio-Yandex-Practicum/maxboom_frontend, pull requests merged in 2024-06, with the labels that each got.

#404 #403-category-id-bug
  src/pages/ProductsPage/ProductsPage.tsx
Labels: bug

#400 Development 369 my account page
  src/app/App.tsx
  src/app/router/AppRouter/ui/AppRouter.tsx
  src/app/router/AppRouter/ui/ProtectedRoute.tsx
  src/assets/icons/IconEnvelop.svg
  src/assets/icons/IconFile.svg
  src/entities/CartEntity/model/types/types.ts
  src/entities/Favorite/model/functions/functions.ts
  src/entities/Favorite/model/hooks/useFavorite.ts
  src/entities/Favorite/model/hooks/useWithFavorie.ts
  src/entities/Favorite/model/types/types.ts
  src/entities/HeaderAccount/HeaderAccount.tsx
  src/entities/HeaderAccount/headerAccount.module.scss
  src/entities/SideBarEntity/model/functions/sideBarOptions.ts
  src/features/CartEdit/ui/CartEdit/CartEdit.tsx
  src/features/SideBarMenuModal/ui/SideBarMenuModal.stories.tsx
  src/features/SideBarMenuModal/ui/SideBarMenuModal.tsx
  src/features/login/model/hooks/useLogout.tsx
  src/features/login/model/selectors/getUserAuthStatus.ts
  src/features/login/model/services/getCurrentUser/getCurrentUser.ts
  src/features/login/model/services/loginByUsername/loginByUsername.ts
  src/features/login/model/services/logout/logout.ts
  src/features/login/model/slice/loginSlice.ts
  src/features/login/model/types/types.ts
  src/pages/AccountPage/AccountPage.module.scss
  src/pages/AccountPage/AccountPage.tsx
  src/pages/CategoryPage/CategoryPage.module.scss
  src/pages/FavoritesPage/FavoritesPage.module.scss
  src/pages/FavoritesPage/FavoritesPage.tsx
  src/pages/FormReturnPage/FormReturnPage.tsx
  src/pages/LogoutPage/LogoutPage.module.scss
  src/pages/LogoutPage/LogoutPage.tsx
  src/pages/ProductsPage/types/types.ts
  src/shared/api/api.ts
  src/shared/api/types.ts
  src/shared/config/routerConfig/routes.ts
  src/shared/model/types/ImageModel.ts
  src/shared/model/types/ProductModel.ts
  src/shared/ui/ContextMenuElement/ContextMenuElement.tsx
  src/shared/ui/ContextMenuElement/contextMenuElement.module.scss
  src/widgets/AccountCart/AccountCart.module.scss
  src/widgets/AccountCart/AccountCart.stories.tsx
  src/widgets/AccountCart/AccountCart.tsx
  src/widgets/AccountCart/models/functions/functions.ts
  src/widgets/AccountCart/ui/AccountCartCard/AccountCartCard.module.scss
  src/widgets/AccountCart/ui/AccountCartCard/AccountCartCard.tsx
  src/widgets/AccountMenu/AccountMenu.module.scss
  src/widgets/AccountMenu/AccountMenu.stories.tsx
  src/widgets/AccountMenu/AccountMenu.tsx
  src/widgets/AccountSubscribe/AccountSubscribe.module.scss
  src/widgets/AccountSubscribe/AccountSubscribe.stories.tsx
  src/widgets/AccountSubscribe/AccountSubscribe.tsx
  src/widgets/LastOrder/LastOrder.module.scss
  src/widgets/LastOrder/LastOrder.stories.tsx
  src/widgets/LastOrder/LastOrder.tsx
  src/widgets/ProductsList/ProductsList.tsx
  src/widgets/SideBarMenu/index.tsx
  src/widgets/SideBarMenu/ui/SideBarMenu/SideBarMenu.module.scss
  src/widgets/SideBarMenu/ui/SideBarMenu/SideBarMenu.stories.tsx
  src/widgets/SideBarMenu/ui/SideBarMenu/SideBarMenu.tsx
  src/widgets/SideBarMenu/ui/withAdaptiveSideBar/withAdaptiveSideBar.tsx
Labels: enhancement, development

#402 Расключил страницу корзины на работу со слайсом корзины из entities. …
  src/app/App.tsx
  src/app/providers/StoreProvider/config/StateSchema.ts
  src/app/providers/StoreProvider/config/store.ts
  src/entities/CartEntity/model/hooks/cartHooks.ts
  src/entities/CartEntity/model/selectors/selectors.ts
  src/entities/CartEntity/model/services/addToCart.ts
  src/entities/CartEntity/model/services/getCart.ts
  src/entities/CartEntity/model/services/putDecreaseProductAmount.ts
  src/entities/CartEntity/model/services/putIncreaseProductAmount.ts
  src/entities/CartEntity/model/services/putRemoveProduct.ts
  src/entities/CartEntity/model/services/putRenewProductAmount.ts
  src/entities/CartEntity/model/slice/cartEntitySlice.ts
  src/entities/CartEntity/model/types/types.ts
  src/features/CartEdit/model/constants/constants.ts
  src/features/CartEdit/model/selectors.ts
  src/features/CartEdit/model/services/putRenewProductAmount.ts
  src/features/CartEdit/model/slice/productAmountSlice.ts
  src/features/CartEdit/model/types.ts
  src/features/CartEdit/ui/CartEdit/CartEdit.stories.tsx
  src/features/CartEdit/ui/CartEdit/CartEdit.tsx
  src/features/login/model/services/loginByUsername/loginByUsername.ts
  src/features/login/model/services/logout/logout.ts
  src/pages/CartPage/CartPage.tsx
  src/pages/CartPage/model/slice.ts
  src/pages/CartPage/model/types.ts
  src/widgets/Header/Header.tsx
Labels: enhancement

#406 enhancement_384_error_page
  src/app/router/AppRouter/ui/AppRouter.tsx
  src/app/styles/base/_reset.scss
  src/assets/images/errorPage/img-page-not-found.webp
  src/pages/ErrorPage/ErrorPage.module.scss
  src/pages/ErrorPage/ErrorPage.tsx
  src/pages/RootPage/RootPage.tsx
  src/pages/RootPage/root.module.scss
  src/shared/config/routerConfig/routes.ts
Labels: enhancement, верстка

#416 Перевел все компоненты на использование типа IProduct из shared
  src/app/providers/StoreProvider/config/StateSchema.ts
  src/entities/Favorite/model/functions/functions.ts
  src/features/CardPreviewHeader/CardPreviewHeader.tsx
  src/features/ProductImgCarousel/ProductImgCarousel.tsx
  src/features/ProductImgCarousel/model/functions/functions.ts
  src/features/ProductImgCarousel/model/types/productImgCarouselType.ts
  src/features/ProductImgCarousel/ui/PreviewCarousel/PreviewCarousel.tsx
  src/pages/CartPage/CartPage.tsx
  src/pages/ProductPage/model/functions/functions.ts
  src/pages/ProductPage/model/slice/productSlice.ts
  src/pages/ProductPage/model/types/productTypes.ts
  src/pages/ProductsPage/types/types.ts
  src/shared/model/types/ProductCartListModel.ts
  src/shared/model/types/ProductModel.ts
  src/shared/ui/ProductLabels/ProductLabels.stories.tsx
  src/shared/ui/ProductLabels/ProductLabels.tsx
  src/widgets/Carousel/Carousel.stories.tsx
  src/widgets/Carousel/Carousel.tsx
  src/widgets/Product/Product.tsx
  src/widgets/Product/model/types/productTypes.ts
  src/widgets/ProductInfo/ProductInfo.tsx
  src/widgets/ProductItem/CardPreview/CardPreview.tsx
  src/widgets/ProductItem/ProductItem.stories.tsx
  src/widgets/ProductItem/ProductItem.tsx
  src/widgets/ProductsList/ProductsList.tsx
  src/widgets/ViewedProducts/model/functions/functions.ts
  src/widgets/ViewedProducts/model/types/types.ts
  src/widgets/ViewedProducts/ui/ViewedProducts.tsx
Labels: enhancement

#417 Добавил недостающие руты в меню О нас в хедер
  src/app/router/AppRouter/ui/AppRouter.tsx
  src/components/BlogMain/BlogMain.tsx
  src/entities/ReviewCard/ui/ReviewCardFeedback/ReviewCardFeedback.tsx
  src/entities/ReviewCard/ui/ReviewCardStore/ReviewCardStore.tsx
  src/mockData/headerMenuData.ts
  src/pages/AboutUsPage/AboutUsPage.tsx
  src/pages/AccountPage/AccountPage.tsx
  src/pages/BlogPage/BlogPage.tsx
  src/pages/CartPage/CartPage.tsx
  src/pages/ComparePage/ComparePage.tsx
  src/pages/ContactsPage/ContactsPage.tsx
  src/pages/DeliveryPage/DeliveryPage.tsx
  src/pages/ErrorPage/ErrorPage.tsx
  src/pages/FavoritesPage/FavoritesPage.tsx
  src/pages/FeedbackPage/FeedbackPage.tsx
  src/pages/FormReturnPage/FormReturnPage.tsx
  src/pages/HelpPage/HelpPage.tsx
  src/pages/LoginPage/LoginPage.tsx
  src/pages/LogoutPage/LogoutPage.tsx
  src/pages/MainPage/MainPage.tsx
  src/pages/PrivacyPage/PrivacyPage.module.scss
  src/pages/PrivacyPage/PrivacyPage.tsx
  src/pages/ProductPage/ProductPage.tsx
  src/pages/ProductsPage/ProductsPage.tsx
  src/pages/ReviewsPage/ReviewsPage.module.scss
  src/pages/ReviewsPage/ReviewsPage.tsx
  src/pages/SearchResultsPage/SearchResultsPage.tsx
  src/pages/TermsPage/TermsPage.module.scss
  src/pages/TermsPage/TermsPage.tsx
  src/pages/VouchersPage/VouchersPage.tsx
  src/shared/config/routerConfig/routes.ts
  src/shared/libs/helpers/scrollPageToTop.ts
  src/shared/mockData/catalogListData.ts
  src/shared/ui/WrapperForMainContent/WrapperForMainContent.tsx
  src/shared/ui/WrapperForMainContent/wrapper.module.scss
  src/widgets/FeedbackList/FeedbackList.tsx
  src/widgets/ReviewsBlock/ui/ReviewsBlock.tsx
Labels: enhancement

#431 enhancement_425_cart_cards
  src/entities/ProductEntity/ui/ProductEntity/ProductEntity.module.scss
  src/entities/ProductEntity/ui/ProductEntity/ProductEntity.tsx
  src/features/CartEdit/ui/CartEdit/CartEdit.module.scss
  src/features/CartEdit/ui/CartEdit/CartEdit.tsx
  src/pages/CartPage/CartPage.module.scss
  src/pages/CartPage/CartPage.tsx
Labels: enhancement, верстка

#432 enhancement_426_main_page_news
  src/entities/NewsCard/NewsCard.module.scss
  src/entities/NewsCard/NewsCard.stories.tsx
  src/entities/NewsCard/index.tsx
  src/entities/NewsCard/ui/NewsCard.module.scss
  src/entities/NewsCard/ui/NewsCard.stories.tsx
  src/entities/NewsCard/ui/NewsCard.tsx
  src/widgets/NewsBlock/ui/NewsBlock.tsx
Labels: refactoring

#435 Bug 427 login page
  src/entities/SideBarEntity/model/functions/sideBarOptions.ts
  src/features/login/ui/LoginForm/LoginForm.tsx
Labels: bug

#433 Enhancement 429 product card
  src/assets/icons/WB.svg
  src/entities/WidgetButtonsPurchase/WidgetButtonsPurchase.module.scss
  src/entities/WidgetButtonsPurchase/WidgetButtonsPurchase.stories.tsx
  src/entities/WidgetButtonsPurchase/WidgetButtonsPurchase.tsx
  src/features/ProductItem/CardPreview/CardPreview.module.scss
  src/features/ProductItem/CardPreview/CardPreview.tsx
  src/features/ProductItem/ProductItem.tsx
  src/widgets/Product/Product.module.scss
  src/widgets/Product/Product.tsx
  src/widgets/ProductsList/ProductsList.tsx
  src/widgets/ViewedProducts/ui/ViewedProducts.tsx
Labels: enhancement

#419 #411-enhancement-create-ShopNewsPage
  src/app/router/AppRouter/ui/AppRouter.tsx
  src/entities/NewsCard/ui/NewsCard.module.scss
  src/pages/ShopNewsPage/ShopNewsPage.module.scss
  src/pages/ShopNewsPage/ShopNewsPage.tsx
  src/shared/config/routerConfig/routes.ts
  src/widgets/NewsBlock/ui/ShopNewsWidget/ShopNewsWidget.module.scss
  src/widgets/NewsBlock/ui/ShopNewsWidget/ShopNewsWidget.stories.tsx
  src/widgets/NewsBlock/ui/ShopNewsWidget/ShopNewsWidget.tsx
Labels: enhancement, верстка

#407 #365-enhancement-create-SubscriptionPage
  src/app/router/AppRouter/ui/AppRouter.tsx
  src/pages/SubscriptionPage/SubscriptionPage.module.scss
  src/pages/SubscriptionPage/SubscriptionPage.tsx
  src/shared/config/routerConfig/routes.ts
  src/widgets/AccountSubscribe/AccountSubscribe.tsx
  src/widgets/DistributionForm/modal/types.ts
  src/widgets/DistributionForm/ui/DistributionForm.module.scss
  src/widgets/DistributionForm/ui/DistributionForm.stories.tsx
  src/widgets/DistributionForm/ui/DistributionForm.tsx
Labels: enhancement, верстка

#438 Bug 436 registration page
  src/app/providers/StoreProvider/config/StateSchema.ts
  src/app/providers/StoreProvider/config/store.ts
  src/app/router/AppRouter/ui/AppRouter.tsx
  src/features/login/ui/LoginForm/LoginForm.tsx
  src/pages/CreateAccountPage/CreateAccountPage.module.scss
  src/pages/CreateAccountSuccess/CreateAccountSuccess.module.scss
  src/pages/CreateAccountSuccess/CreateAccountSuccess.tsx
  src/pages/ShopNewsPage/ShopNewsPage.tsx
  src/pages/SubscriptionPage/SubscriptionPage.tsx
  src/shared/api/types.ts
  src/shared/config/routerConfig/routes.ts
  src/widgets/CreateAccount/model/services/createAccount/createAccount.ts
  src/widgets/CreateAccount/model/slice/loginSlice.ts
  src/widgets/CreateAccount/model/types.ts
  src/widgets/CreateAccount/model/types/types.ts
  src/widgets/CreateAccount/model/validation/validation.ts
  src/widgets/CreateAccount/ui/CreateAccountForm.module.scss
  src/widgets/CreateAccount/ui/CreateAccountForm.tsx
Labels: bug, api

#439 Удалил заголовок на странице авторизации
  src/pages/LoginPage/LoginPage.tsx
Labels: bug

#440 Development 424 edit account page
  src/app/providers/StoreProvider/config/StateSchema.ts
  src/app/providers/StoreProvider/config/store.ts
  src/app/router/AppRouter/ui/AppRouter.tsx
  src/entities/SideBarEntity/model/functions/sideBarOptions.ts
  src/features/RequiredFieldTitle/RequiredFieldTitle.module.scss
  src/features/RequiredFieldTitle/RequiredFieldTitle.tsx
  src/features/login/model/selectors/getUserAuthStatus.ts
  src/features/login/model/slice/loginSlice.ts
  src/features/login/model/types/types.ts
  src/pages/EditAccountPage/EditAccountPage.module.scss
  src/pages/EditAccountPage/EditAccountPage.tsx
  src/shared/api/types.ts
  src/shared/config/routerConfig/routes.ts
  src/shared/constants/constants.ts
  src/shared/ui/Checkbox/Checkbox.tsx
  src/widgets/CreateAccount/ui/CreateAccountForm.tsx
  src/widgets/EditAccount/EditAccount.module.scss
  src/widgets/EditAccount/EditAccount.tsx
  src/widgets/EditAccount/model/constants/constants.ts
  src/widgets/EditAccount/model/functions/functions.ts
  src/widgets/EditAccount/model/scheme/editAccountFormSliceScheme.ts
  src/widgets/EditAccount/model/slice/editAccountFormSlice.ts
  src/widgets/EditAccount/model/validation/editAccountFormScheme.ts
  src/widgets/FeedbackForm/FeedbackForm.tsx
  src/widgets/FeedbackForm/ui/FeedbackFormRadioGroup/FeedbackFormRadioGroup.tsx
Labels: development
