Repository Studio-Yandex-Practicum/maxboom_frontend, pull requests merged in 2024-05, with the labels that each got.

#337 enhancement_308_header_categories_skeleton
  src/entities/Category/selectors/categorySelectors.ts
  src/entities/Category/slice/categorySlice.ts
  src/entities/Category/types/types.ts
  src/shared/ui/CatalogLink/ui/skeleton/CatalogLinkSkeleton.tsx
  src/widgets/Header/Header.tsx
  src/widgets/Header/header.module.scss
Labels: enhancement, верстка

#334 enhancement_333_sidebar_menu
  src/assets/images/sideBarMenu/IconArrowDown.svg
  src/features/CartEdit/ui/CartEdit/CartEdit.module.scss
  src/features/SideBar/index.tsx
  src/features/SideBar/ui/SideBar.module.scss
  src/features/SideBar/ui/SideBar.stories.tsx
  src/features/SideBar/ui/SideBar.tsx
  src/mockData/sideBarProfileData.ts
  src/pages/FormReturnPage/FormReturnPage.tsx
  src/widgets/SideBarMenu/index.tsx
  src/widgets/SideBarMenu/ui/SideBarMenu.module.scss
  src/widgets/SideBarMenu/ui/SideBarMenu.stories.tsx
  src/widgets/SideBarMenu/ui/SideBarMenu.tsx
Labels: enhancement, верстка

#344 Enhancement 338 sidebar menu modal
  src/assets/icons/iconCategory.svg
  src/assets/images/sideBarMenu/IconArrowDown.svg
  src/assets/images/sideBarMenu/iconCategory.svg
  src/entities/SideBarButton/index.tsx
  src/entities/SideBarButton/ui/SideBarButton.module.scss
  src/entities/SideBarButton/ui/SideBarButton.stories.tsx
  src/entities/SideBarButton/ui/SideBarButton.tsx
  src/features/SideBar/ui/SideBar.module.scss
  src/features/SideBarMenuModal/SideBarLink/SideBarLink.module.scss
  src/features/SideBarMenuModal/SideBarLink/SideBarLink.tsx
  src/features/SideBarMenuModal/SideBarSublinks/SideBarSublinks.module.scss
  src/features/SideBarMenuModal/SideBarSublinks/SideBarSublinks.tsx
  src/features/SideBarMenuModal/index.tsx
  src/features/SideBarMenuModal/model/types/types.ts
  src/features/SideBarMenuModal/ui/SideBarMenuModal.module.scss
  src/features/SideBarMenuModal/ui/SideBarMenuModal.stories.tsx
  src/features/SideBarMenuModal/ui/SideBarMenuModal.tsx
  src/pages/FormReturnPage/FormReturnPage.tsx
Labels: enhancement, верстка

#349 Layout 342 footer
  src/entities/Payments/Payments.tsx
  src/features/SubscribeForm/SubscribeForm.module.scss
  src/features/SubscribeForm/SubscribeForm.stories.ts
  src/features/SubscribeForm/SubscribeForm.tsx
  src/features/SubscribeForm/model/constants/constants.ts
  src/features/SubscribeForm/model/types/types.ts
  src/features/SubscribeForm/model/validationSchema/validationSchema.ts
  src/shared/ui/FormMsg/FormMsg.module.scss
  src/shared/ui/FormMsg/FormMsg.stories.tsx
  src/shared/ui/FormMsg/FormMsg.tsx
  src/shared/ui/FormMsg/model/types/types.ts
  src/widgets/FeedbackForm/FeedbackForm.tsx
  src/widgets/Footer/Footer.module.scss
  src/widgets/Footer/Footer.tsx
Labels: enhancement, верстка

#351 Enhancement 289 favorite page
  src/app/router/AppRouter/ui/AppRouter.tsx
  src/entities/Favorite/model/functions/functions.ts
  src/entities/Favorite/model/hooks/useFavorite.ts
  src/entities/Favorite/model/hooks/useWithFavorie.ts
  src/entities/Favorite/model/types/types.ts
  src/pages/FavoritesPage/FavoritesPage.module.scss
  src/pages/FavoritesPage/FavoritesPage.tsx
  src/shared/constants/constants.ts
  src/shared/constants/sessionStorage.ts
  src/widgets/Footer/Footer.module.scss
  src/widgets/Product/Product.tsx
  src/widgets/ProductItem/CardPreview/CardPreview.tsx
  src/widgets/ProductItem/CardPreview/CardPrewiew.stories.tsx
  src/widgets/ProductItem/ProductItem.tsx
Labels: enhancement, верстка

#346 enhancement_341_header_adaptive
  src/assets/icons/iconMenu.svg
  src/assets/icons/iconSearch.svg
  src/entities/HeaderAccount/HeaderAccount.tsx
  src/entities/HeaderAccount/headerAccount.module.scss
  src/features/SearchProduct/ui/SearchProduct.module.scss
  src/shared/ui/CatalogLink/ui/skeleton/CatalogLinkSkeleton.tsx
  src/shared/ui/ContextMenuElement/ContextMenuElement.tsx
  src/shared/ui/ContextMenuElement/contextMenuElement.module.scss
  src/shared/ui/logo/Logo.tsx
  src/shared/ui/logo/logo.module.scss
  src/widgets/Header/Header.tsx
  src/widgets/Header/header.module.scss
Labels: enhancement

#343 #316-api-renew-product-amount
  src/entities/ProductEntity/ui/ProductEntity/ProductEntity.tsx
  src/features/CartEdit/model/services/putRenewProductAmount.ts
  src/features/CartEdit/model/slice/productAmountSlice.ts
  src/features/CartEdit/model/types.ts
  src/features/CartEdit/ui/CartEdit/CartEdit.tsx
  src/shared/api/types.ts
Labels: enhancement, api

#376 Исправил валидацию формы логина. Исправил эндпоинты для логина и разл…
  src/features/login/model/services/loginByUsername/loginByUsername.ts
  src/features/login/model/services/logout/logout.ts
  src/features/login/model/slice/loginSlice.ts
  src/features/login/model/validation/validation.ts
Labels: api

#373 В компонент Scroll добавлен необязательный пропс, позволяющий скролит…
  src/shared/ui/Scroll/Scroll.tsx
  src/widgets/ReviewsBlock/ui/ReviewsBlock/ReviewsBlock.tsx
  src/widgets/ReviewsBlock/ui/ReviewsBlock/reviewsBlock.module.scss
  src/widgets/ViewedProducts/ViewedProducts.module.scss
  src/widgets/ViewedProducts/ViewedProducts.tsx
Labels: enhancement

#375 enhancement_374_header_mobile_search_modal
  src/entities/HeaderAccount/HeaderAccount.tsx
  src/entities/HeaderAccount/headerAccount.module.scss
  src/entities/ModalHeading/index.tsx
  src/entities/ModalHeading/ui/ModalHeading.module.scss
  src/entities/ModalHeading/ui/ModalHeading.stories.tsx
  src/entities/ModalHeading/ui/ModalHeading.tsx
  src/entities/SearchResult/SearchResult.module.scss
  src/features/HeaderMenuModal/ui/HeaderMenuModal.module.scss
  src/features/HeaderMenuModal/ui/HeaderMenuModal.tsx
  src/features/HeaderSearchModal/index.tsx
  src/features/HeaderSearchModal/ui/HeaderSearchModal.module.scss
  src/features/HeaderSearchModal/ui/HeaderSearchModal.stories.tsx
  src/features/HeaderSearchModal/ui/HeaderSearchModal.tsx
  src/features/SearchProduct/ui/SearchProduct.module.scss
  src/features/SearchProduct/ui/SearchProduct.tsx
  src/shared/ui/Input/Input.module.scss
  src/shared/ui/Input/Input.tsx
  src/widgets/Header/Header.tsx
Labels: enhancement, верстка

#345 #319-remove-product-from-cart
  src/features/CartEdit/model/selectors.ts
  src/features/CartEdit/model/services/putRemoveProduct.ts
  src/features/CartEdit/model/slice/productAmountSlice.ts
  src/features/CartEdit/model/types.ts
  src/features/CartEdit/ui/CartEdit/CartEdit.stories.tsx
  src/features/CartEdit/ui/CartEdit/CartEdit.tsx
  src/pages/CartPage/CartPage.tsx
  src/shared/api/types.ts
  src/shared/libs/helpers/calculateProductPrice.ts
Labels: enhancement, api

#380 #378-bug-fix
  src/features/CartEdit/model/selectors.ts
  src/features/CartEdit/model/services/putRenewProductAmount.ts
  src/features/CartEdit/model/slice/productAmountSlice.ts
  src/features/CartEdit/ui/CartEdit/CartEdit.tsx
Labels: bug

#348 #339-pagination
  package-lock.json
  package.json
  src/app/providers/StoreProvider/config/StateSchema.ts
  src/app/providers/StoreProvider/config/store.ts
  src/components/Dropdown/Dropdown.tsx
  src/components/PageControls/PageControls.tsx
  src/components/Pagination/Pagination.tsx
  src/components/Pagination/selectors/selectors.tsx
  src/components/Pagination/slice/paginationSlice.tsx
  src/components/Pagination/types/types.ts
  src/features/CategoryItem/CategoryItem.tsx
  src/pages/ProductsPage/ProductsPage.tsx
  src/pages/ProductsPage/services/getProducts.ts
  src/shared/libs/helpers/totalPagesHandler.ts
  src/shared/libs/hooks/useReplaceValueFromLocation.ts
  src/shared/ui/CategoryCard/ui/CategoryCard.tsx
  src/widgets/CatalogNodeItem/CatalogNodeItem.tsx
  src/widgets/Header/Header.tsx
Labels: enhancement

#392 enhancement_377_login_form_adaptive_new
  src/components/WrapperForMainContent/wrapper.module.scss
  src/features/WidgetButtonsPurchase/WidgetButtonsPurchase.module.scss
  src/features/WidgetButtonsPurchase/WidgetButtonsPurchase.tsx
  src/features/login/ui/LoginForm/LoginForm.module.scss
  src/features/login/ui/LoginForm/LoginForm.stories.tsx
  src/features/login/ui/LoginForm/LoginForm.tsx
  src/widgets/Product/Product.module.scss
  src/widgets/Product/Product.tsx
  src/widgets/ProductItem/CardPreview/CardPreview.module.scss
  src/widgets/ProductItem/CardPreview/CardPreview.tsx
Labels: enhancement

#391 Заменил моковыве данные в корзине в шапке на реальные данные из слайс…
  src/entities/HeaderAccount/HeaderAccount.stories.tsx
  src/entities/HeaderAccount/HeaderAccount.tsx
  src/features/HeaderMenuModal/ui/HeaderMenuModal.stories.tsx
  src/features/HeaderMenuModal/ui/HeaderMenuModal.tsx
  src/widgets/Header/Header.tsx
Labels: bug

#393 Enhancement 381 favorite page
  src/pages/FavoritesPage/FavoritesPage.module.scss
  src/pages/FavoritesPage/FavoritesPage.tsx
Labels: enhancement
